debug: false
displays:
  samsung_ultrawide:
    default_padding: 8
    stop_manage_at: 4
    uuid: <insert your own uuid. Find here --> yabai -m query --displays>
    window_count_1:
      padding: 1700
    window_count_2:
      padding: 850
    window_count_3:
      flip: true
      padding: default_padding
log_file: resize_ultrawide.log
managed: true
space:
  s_1:
    managed: true
  s_10:
    managed: false
  s_2:
    managed: true
  s_3:
    managed: true
  s_4:
    managed: true
  s_5:
    managed: true
  s_6:
    managed: true
  s_7:
    managed: true
  s_8:
    managed: false
  s_9:
    managed: false


windows_blacklist:
  app:
  - System Settings
  - zoom.us
  subrole:
  - AXDialog
  title:
  - Outlook
  - Calendar
  - 1 Reminder
  - 2 Reminders
  - 3 Reminders
  - 4 Reminders
